version: "3.8"

services:
  localstack:
    image: localstack/localstack:3.8.0
    ports:
      - "127.0.0.1:4566:4566"            # LocalStack Gateway
      - "127.0.0.1:4510-4559:4510-4559"  # external services port range
    environment:
      - DEBUG=${DEBUG:-0}
      - DOCKER_HOST=unix:///var/run/docker.sock
    volumes:
      - "${LOCALSTACK_VOLUME_DIR:-./volume}:/var/lib/localstack"
      - "/var/run/docker.sock:/var/run/docker.sock"
      - "./localstack-init:/etc/localstack/init/ready.d"

  worker:
    build:
      context: ./worker-fastapi
      dockerfile: Dockerfile
    ports:
      - "8000:8000"
    environment:
      - AWS_SQS_QUEUE_URL=http://localstack:4566/000000000000/odiseo-materials-queue
      - AWS_SQS_ENDPOINT=http://localstack:4566
      - AWS_S3_ENDPOINT=http://localstack:4566
      - AWS_REGION=us-east-1
      - AWS_S3_BUCKET_NAME=odiseo-materials
      - AWS_ACCESS_KEY_ID=test
      - AWS_SECRET_ACCESS_KEY=test
      - B2B_WEBHOOK_URL=http://host.docker.internal:3000/v1/materials/webhook/status
    extra_hosts:
      - "host.docker.internal:host-gateway"
    depends_on:
      - localstack

  redis:
    image: redis:7.2-alpine
    ports:
      - "127.0.0.1:6380:6379"
